### PR TITLE
Update README.md to point to new home for iOSSnapshotTestCase

### PR DESCRIPTION
**Pull request by alanzeino**
Facebook and Uber have agreed to move FBSnapshotTestCase to new stewardship over on Uber's github page. 

As a large user of this library we're happy to maintain the library in future and give it some love.

Thanks!

### CODE REVIEW

**Comment by nscoding** [comment]
Thanks @alanzeino so much! I am glad to see this PR and looking forward to see what you guys will build. <3

**Comment by freak4pc** [comment]
Incredible ! So happy to hear this is going to get proper support. Really great news.

**Comment by freak4pc** [comment]
Just for the sake of community-involvement and open discussion, is there any timeline regarding transferring ownership of this repo over to Uber ? 

I think many developers are worried adding a new dependency that is still under "Facebook Archive" 😄

**Comment by TheAdamBorek** [comment]
👍 - really great news! The library is great for 99% of the projects 

> I think many developers are worried adding a new dependency that is still under "Facebook Archive"

Yeah, I'm was one of them as I would like to add it to new project :)

**Comment by freak4pc** [comment]
Hey Guys, Happy new year everyone :) 

Are there any new developments in moving stewardship over to Uber? Anything us as the community can do to help ?

**Comment by alanzeino** [comment]
Totally understand everyone's waiting — over on our side we just want to be good citizens of open source and wait for Facebook to point to our repo before we open the doors. Hopefully they can merge this soon!

**Comment by freak4pc** [comment]
That 100% makes sense :) 

Actually thought the ball was in Uber’s court, so good to know where it stands.

Many thanks for your update !

**Comment by freak4pc** [comment]
@nscoding Are there any updates from the Facebook said you could share perhaps ?

**Comment by JoelMarcey** [comment]
Merging now....

**Comment by freak4pc** [comment]
<p align="center"></p>

**Comment by freak4pc** [comment]
We're a go! @alanzeino 
Really looking forward to seeing the new repo :)

**Comment by alanzeino** [comment]
Thanks @JoelMarcey — we're going to open the new repo and get the podspec uploaded asap.

**Pull request merged**
